### ISSUE TITLE
Allowing access to Mythtv backend through openvpn client

### ISSUE THREAD

**Issue by born-daniel** [oakesville/mythling#101]
I have an openvpn VPN set up at home and I would love to be able to access it from Mythling when I am away, through the openvpn client set up on my Android 9 phone.

I have other apps (like Mythmote, Squeeze Controller and JuiceSSH) that work just fine but I cannot get it working with Mythling, I get Java exceptions no matter what I try.

Thanks,
Daniel

**Comment by JohnHH** [comment]
This could be a backend configuration issue. I was just trying this, and the device on the other end of the VPN was put in a different subnet, and this error showed up in the mythbackend log file:
 HttpServer89 mythcorecontext.cpp:1277 (CheckSubnet) - MythCoreContext::CheckSubnet(): Repeat denied connection from ip address: [ip of device connected via VPN]

Check the allow connection from all setting, it may be off. Better off controlling access via a firewall than this setting, but an exposed backend allows all kinds of mischief. I didn't find the setting in the UI where it had been documented in v29, but running v31, so I just hacked it into the database and restarted the backend, and mythling now works over VPN:

update settings set data = 1 where value = 'AllowConnFromAll' ;

**Comment by born-daniel** [comment]
My phone shows a Java IO exception but my backend complains about "CheckSubnet(): Denied connection from iP address xx.xx.xx.xx which is the one I use for the VPN...
good catch! I never thought it even made it to the backend.

**Comment by born-daniel** [comment]
I just tried it now and it works!
Awesome! Thank you very much for answering this! 
I will close this issue now.
