### ISSUE TITLE
parsing bug in media.php 

### ISSUE THREAD

**Issue by frank16** [oakesville/mythling#42]
When a video filename has multiple '.' symbols, the 'type'  gets messed up, something like "donald.duck.avi"

**Comment by oakesville** [comment]
Yes, I can confirm that this definitely is a Mythling Services parsing bug in media.php.  I'll fix this as soon as possible on the 1.2 branch.  Luckily since it's isolated to media.php, the fix can be retrofitted to Mythling 1.1.

Thanks,
 - Don

**Comment by oakesville** [comment]
Fixed on branch rel-1.2.
