### ISSUE TITLE
"external app" video player is grayed out - version 1.2.08 on Amazon Fire Stick

### ISSUE THREAD

**Issue by play3r** [oakesville/mythling#59]
In setup, under "video player" the "external app" cannot be selected.  As soon as a video is selected to player the Mythling app closes.

This is on an Amazon Fire Stick.

The Mythling version is 1.2.08

**Comment by oakesville** [comment]
I think it's possible that what you perceive to be disabled is actually just a quirk in the way Fire TV renders these preference toggles (showing disabled if the switch is in the OFF position).  This nuisance is covered by issue #45.

Either way, of course, Mythling should not crash when a video is played.  It would be helpful if you can enable error reporting under the Connections settings and then try playing a video using both the internal and external player options.  If you let me know once you've done that I'll look into the error reports and see if I can figure out the problem.

It would help if you can let me know which of the [FireTV Installation Methods](https://github.com/oakesville/mythling/wiki/Mythling-On-Fire-TV#user-content-installation) you used.

Thanks,
 - Don

**Comment by play3r** [comment]
Hi Don,

By fiddling around with the settings, I got mythling to display videos 
in a "detail" mode (I think that's what it's called.)  See attached.

When I click on the play button (outlined in orange) mythling gives me 
the chose of external player.  I used "MX Player" and it played fine.

MythTV FrontEnd on a Fire Stick.  Very cool.

Thanks,
Mike

**Comment by oakesville** [comment]
I'm glad to hear that you worked it out, Mike.  If you come across any clues that would help me solve your original problem, please pass them along.  Thanks, - Don

**Comment by play3r** [comment]
I don't want to reconfigure it again for fear of losing what I have.  
However, if it resets for any reason, I'll try and debug in a more 
orderly fashion.

Thanks again for your good work.

Mike

**Comment by oakesville** [comment]
Fix implemented based on Amazon dev console error stack trace.
