### ISSUE TITLE
isConnected failed: ECONNREFUSED

### ISSUE THREAD

**Issue by davidrivers** [oakesville/mythling#79]
I just installed Mythling version _2.0.06 (sdk 22)_ from the Google Play Store onto my Nexus 10 (running _Android 5.1.1_). I configured MythTV (version _mythtv 2:0.27.1+fixes.20140624.aa822f5-0ubuntu6_) to be "friendly for Mythling access", using [these configuration settings](https://github.com/oakesville/mythling/wiki). Then, I followed [these instructions](http://oakesville.github.io/mythling/help.html) to configure Mythling on my Nexus 10--I made sure to use the IP address (and not the loopback address, as advised) as the "INTERNAL BACKEND" and checked that "Network" is set to "Internal". I also tried setting connecting to port 6543 to no avail (as well as resetting that value back to the default, 6544, which I believe is correct). Unfortunately, whenever Mythling tries to connect to my MythTV Backend, I get the following connection error:

`java.net.ConnectException: failed to connect to /192.168.1.141 (port 6544) after 6000ms: isConnected failed: ECONNREFUSED (Connection refused)`

And the odd thing is that this error message is shown immediately and not after a 6000 ms timeout, as indicated in the error message that is displayed briefly on the bottom of the screen. I've also checked _mythbackend.log_ and this file shows no record of the failed connection attempt, so I imagine that Mythling isn't even hitting my backend to begin with.

Please be aware that I _just_ installed MythTV earlier today, and after quite a bit of configuring, I was finally able to correctly add my channels (using data from SchedulesDirect.org) and then successfully view them from MythTV Frontend. It is likely that I am making some kind of stupid mistake, but for the life of me I haven't yet been able to identify which stupid mistake I'm making! Please help me troubleshoot this. Mythling looks like a great app I want to use!

**Comment by oakesville** [comment]
Try accessing the MythTV recordings service directly from a browser: 
```http://mythbe_ip:6544/Dvr/GetRecordedList?Descending=true```
Maybe this'll give you some indication as whether or not there's a general connectivity issue.

**Comment by davidrivers** [comment]
@oakesville, Looks like that XML end point works fine: https://gist.github.com/davidrivers/a2e58e1bee62ec43c829b89c05b83f41

**Comment by davidrivers** [comment]
Oddly the `--setverbose` flag prevents `mythbackend` from starting, but I was just able to connect with Mythling after running `mythbackend` in a terminal. Maybe the backend wasn't running when I was attempting to connect with Mythling, but somehow I was still able to use the frontend with no problem and also view live channels using other UPnP clients.

I'm really confused as to what exactly I was doing wrong before, but I suspect that maybe some of the settings I had configured hadn't yet taken place. Anyway, it seems that my Mythling issue is fixed--although it's now been replaced with a mysterious "Handling segmentation fault" error message that kills mythbackend after a few moments :(

Thanks for the attention anyway! Looking forward to using Mythling more once I'm able to keep my backend running smoothly...
